[tox]
envlist = docs, django{42,52}
requires = tox-uv>=1

[testenv]
runner = uv-venv-lock-runner
changedir = {toxinidir}/testproject/
dependency_groups =
    django42: django42
    django52: test
allowlist_externals = make
commands =
    make -C {toxinidir} test

[testenv:docs]
runner = uv-venv-lock-runner
changedir = {toxinidir}
dependency_groups = doc
allowlist_externals = make
commands =
    make docs
